trigger:
- master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: artifactz-extension

stages:
  - stage: Run_and_publish_unit_tests
    jobs:
      - job:
        steps:
          - task: TfxInstaller@4
            inputs:
              version: "v0.x"
          - task: Npm@1
            displayName: Install dependencies in the publishArtifactTask directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/publishArtifactTask'
          - task: Bash@3
            displayName: Compile Javascript and install mocha package in the publishArtifactTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/publishArtifactTask
                tsc
                npm install mocha --save-dev
          - task: Npm@1
            displayName: Run unit tests in the publishArtifactTask directory
            inputs:
              command: 'custom'
              workingDir: 'buildTasks/publishArtifactTask'
              customCommand: 'test'
          - task: Npm@1
            displayName: Install dependencies in the pushArtifactTask directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/pushArtifactTask'
          - task: Bash@3
            displayName: Compile Javascript and install mocha package in the pushArtifactTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/pushArtifactTask
                tsc
                npm install mocha --save-dev
          - task: Npm@1
            displayName: Run unit tests in the pushArtifactTask directory
            inputs:
              command: 'custom'
              workingDir: 'buildTasks/pushArtifactTask'
              customCommand: 'test'
          - task: Npm@1
            displayName: Install dependencies in the retrieveArtifactsTask  directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/retrieveArtifactsTask'
          - task: Bash@3
            displayName: Compile Javascript and install mocha package in the retrieveArtifactsTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/retrieveArtifactsTask
                tsc
                npm install mocha --save-dev
          - task: Npm@1
            displayName: Run unit tests in the retrieveArtifactsTask directory
            inputs:
              command: 'custom'
              workingDir: 'buildTasks/retrieveArtifactsTask'
              customCommand: 'test'
          - task: Npm@1
            displayName: Install dependencies in the retrieveArtifactTask  directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/retrieveArtifactTask'
          - task: Bash@3
            displayName: Compile Javascript and install mocha package in the retrieveArtifactTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/retrieveArtifactTask
                tsc
                npm install mocha --save-dev
          - task: Npm@1
            displayName: Run unit tests in the retrieveArtifactTask directory
            inputs:
              command: 'custom'
              workingDir: 'buildTasks/retrieveArtifactTask'
              customCommand: 'test'
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test-result.xml'
  - stage: Package_extension_and_publish_build_artifacts
    jobs:
      - job:
        steps:
          - task: TfxInstaller@4
            inputs:
              version: "v0.7.x"
          - task: Npm@1
            displayName: Install dependencies in the publishArtifactTask directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/publishArtifactTask'
          - task: Bash@3
            displayName: Compile Javascript in the publishArtifactTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/publishArtifactTask
                tsc
          - task: Npm@1
            displayName: Install dependencies in the pushArtifactTask directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/pushArtifactTask'
          - task: Bash@3
            displayName: Compile Javascript in the pushArtifactTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/pushArtifactTask
                tsc
          - task: Npm@1
            displayName: Install dependencies in the retrieveArtifactsTask  directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/retrieveArtifactsTask'
          - task: Bash@3
            displayName: Compile Javascript in the retrieveArtifactsTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/retrieveArtifactsTask
                tsc
          - task: Npm@1
            displayName: Install dependencies in the retrieveArtifactTask  directory
            inputs:
              command: 'install'
              workingDir: 'buildTasks/retrieveArtifactTask'
          - task: Bash@3
            displayName: Compile Javascript in the retrieveArtifactTask directory
            inputs:
              targetType: "inline"
              script: |
                cd buildTasks/retrieveArtifactTask
                tsc
          - task: QueryAzureDevOpsExtensionVersion@4
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'marketplace'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              versionAction: 'Patch'
              outputVariable: 'Task.Extension.Version'
          - task: PackageAzureDevOpsExtension@4
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              extensionVersion: '$(Task.Extension.Version)'
              updateTasksVersion: true
              updateTasksVersionType: 'patch'
              extensionVisibility: 'private' # Change to public if you're publishing to the marketplace
              extensionPricing: 'free'
          - task: CopyFiles@2
            displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
            inputs:
              Contents: "**/*.vsix"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(ArtifactName)'
              publishLocation: 'Container'
  - stage: Download_build_artifacts_and_publish_the_extension
    jobs:
      - job:
        steps:
          - task: TfxInstaller@4
            inputs:
              version: "v0.x"
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "$(ArtifactName)"
              downloadPath: "$(System.DefaultWorkingDirectory)"
          - task: PublishAzureDevOpsExtension@4
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'marketplace'
              fileType: 'vsix'
              vsixFile: '$(ArtifactName)/$(PublisherID).*.vsix'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              updateTasksVersion: false
              extensionVisibility: 'public' # Change to public if you're publishing to the marketplace
              extensionPricing: 'free'
